### ISSUE TITLE
Add input-field for user switching (only for test purposes)

### ISSUE THREAD

**Issue by lukashueller** [bptlab/ark_automate#105]
As a developer, I want to be able to enter an integer number in a simple input field. This field is only for testing purposes and should allow to quickly and easily switch between different users (with different permissions and robots in the future).

**ToDos:** In this issue an input field should be added. Also a dummy function, which is called every time the entered value is changed, should be implemented. Finally, if possible, the current value of the field should be persisted so that the same user is logged in even when the app is restarted. (`user-config.json`)

---

### :thought_balloon: &nbsp; Hints & Thoughts

Please let us use the [ANTD-NumberInput](https://ant.design/components/input-number/) field for this purpose. 

![image](https://user-images.githubusercontent.com/36270527/107122947-2252bf80-689b-11eb-8418-83ac25929e51.png)

---

## :white_check_mark: &nbsp; Conditions of satisfaction

- [ ] Frontend should include an Input-field in the Navbar.
- [ ] Changing the value in the input field should call a dummy function.
- [ ] The current value of the input field should be persisted continuously.

**Comment by kej-jay** [comment]
Based on what attribute of the robots are they being displayed? As far as I know, there is no attribute somewhat related to integers.
Could you please explain it for me and/or maybe reformulate the issue?

**Comment by lukashueller** [comment]
My mistake. I had assumed that the "robotCollaborators" in the header of the SSoT were integers. @WolfgangDaniel  uses strings (usernames) for this. We could handle it that way from my point of view -> then I would suggest a dropdown list of all usernames as input field. What do you think? @kej-jay @SanJSp @MaximilianV

**Comment by kej-jay** [comment]
Imo a user (lets say with the userID '1234TestUser') should regardless of what he/she selects be only able to view those Bots including '1234TestUser' in the collaborators section for that Bot.

**Comment by kej-jay** [comment]
@WolfgangDaniel Warum hast du das noch in den Sprint-Backlog gezogen?
